org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.13
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=mek_compact_machines
mod_name=Mek Compact Machines
mod_license=All Rights Reserved
mod_version=0.0.1
mod_group_id=com.example.mekcompactmachines
mod_authors=toosima-risa
mod_description=Compact Mekanism Multiblocks addon.
minecraft_version=1.20.1
mekanism_version=1.20.1-10.4.5.19
jei_version=15.3.0.4